Add rust http signature
loopholelabs/scale-signature-http pull request #8
Opened 2022-12-05 18:48 UTC by dphilla

2022-12-07 04:40 UTC, dphilla commented
## Description

Adds the default Rust http signature for use in the Scale runtime. This is dependent on changes to `scale` and the `scale-cli` for generation of necessary components. 

## Type of change

Feature

## Testing

Please make sure that existing test cases pass (with `go test ./... -race` and `go test -bench=. ./... -race`),
and if required please add new test cases and list them below:

## Linting

Please make sure you've run the following and fixed any issues that arise:

- [x] `trunk check` has been run

## Final Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-12-07 20:35 UTC, ShivanshVij requested changes
Couple questions and minor changes. 

Next we should also add some tests in https://github.com/loopholelabs/scale-signature-http/blob/staging/runtime_test.go

2022-12-07 20:36 UTC, ShivanshVij commented on http_signature.rs
> +          Ok(res) => res,
@SuperManifolds might be best able to answer this since it's generated code.

2022-12-10 01:07 UTC, dphilla commented on guest.rs
> +           let ptr = PTR.lock().unwrap().clone();
yea, it does.

2022-12-12 18:33 UTC, dphilla commented on http_signature.rs
> +          Ok(res) => res,
This was an added function, for the error handling. Changed to only de-structure the error pattern.

2022-12-13 23:40 UTC, dphilla commented on Cargo.toml
> +polyglot = { git = "https://github.com/loopholelabs/polyglot-rs" }
You can have them point to a commit and version, which works with this form, like:

```
polyglot = { git = "https://github.com/loopholelabs/polyglot-rs", rev = "2172da7", version = "0.1.0" }
```

I was waiting to push this, and polyglot-rs to crates.io until we had everything worked out with the various separation of concerns (crates can't be deleted, just published again w/a version bump), but can go ahead do that for all the generation to work smoothly.

2023-01-25 23:21 UTC, merged